### ISSUE TITLE
Priprava JPA entitet [3 točke]

### ISSUE THREAD

**Issue by nyanSpruk** [bl4ko/PriceRunner#3]
Za entitete vašega podatkovnega modela kreirajte JPA entitete. Zgledujete se lahko po entiteti Izdelek.
```java
@Entity(name = "izdelek")
@NamedQueries(value =
        {
                @NamedQuery(name = "Izdelek.getAll", query = "SELECT o FROM izdelek o")
        })
public class Izdelek {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String ime;

    private String opis;

    private Integer cena;

    @ManyToOne
    @JoinColumn(name = "kategorija_id")
    private Kategorija kategorija;

    // getter in setter metode

}
```

- [x] Poizvedbam getAll dodajte vsaj še tri smiselne @NamedQuery poizvedbe z in brez uporabe parametrov.

**Comment by bl4ko** [comment]
Two entities have been added in [branch](https://github.com/bl4ko/PriceRunner/tree/feat/3-jpa-entitete_all). Two more must be added.
